# Generated by Django 5.2.8 on 2025-11-17 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_profile_full_name_profile_image_alter_profile_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
